// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqfwxkomembxjdkfjttr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZnd4a29tZW1ieGpka2ZqdHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMTQ2NzAsImV4cCI6MjA3Njg5MDY3MH0._f5gngP3DoihqwnMTM_UyAnyYI5pLDwDmTcCEvp86X4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});